#!/bin/bash
# Tạo Bản đồ Repository (Repo Map)
# Quét cấu trúc project và các định nghĩa class/function quan trọng
# Cách dùng: bash .agents/scripts/generate_repomap.sh

OUTPUT_FILE="docs/ai/repomap.txt"

echo "Tạo bản đồ mã nguồn tại $OUTPUT_FILE..."
mkdir -p docs/ai

# Ghi Header
echo "# Repo Map" > "$OUTPUT_FILE"
echo "# Auto-generated by .agents/scripts/generate_repomap.sh" >> "$OUTPUT_FILE"
echo "# Last updated: $(date)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Ghi cấu trúc thư mục (chỉ lấy level 2)
echo "## Cấu trúc thư mục" >> "$OUTPUT_FILE"
if command -v tree &> /dev/null; then
    tree -L 2 -I "venv|node_modules|__pycache__|.git" >> "$OUTPUT_FILE"
else
    find . -maxdepth 2 -not -path "*/\.*" -not -name "venv" -not -name "node_modules" | sort >> "$OUTPUT_FILE"
fi
echo "" >> "$OUTPUT_FILE"

# Quét class/function Python
echo "## Python Classes & Functions" >> "$OUTPUT_FILE"
grep -rE '^(class|def) ' . --include="*.py" | grep -v 'venv' >> "$OUTPUT_FILE" || true
echo "" >> "$OUTPUT_FILE"

# Quét class/function JS/TS
echo "## JS/TS Classes & Functions" >> "$OUTPUT_FILE"
grep -rE '^(class|function|const.*=>)' . --include="*.ts" --include="*.js" | grep -v 'node_modules' >> "$OUTPUT_FILE" || true

echo "✅ Đã tạo xong $OUTPUT_FILE"
